import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Titre } from '../components/Titre'
import { Bouton } from '@/components/Bouton'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-center text-4xl mx-auto text-red-500 '>PPE2</div>
      <div className='text-center text-3xl mx-auto text-red-500'>Bienvenue sur le PPE2 </div> 
      <div className="text-center text-4xl mx-auto text-pink-500">Chat&ToDoList</div>
            
   


    </>
  )
}
